language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

install:
  - mvn clean install
  - mvn cobertura:cobertura
after_success:
  - mvn deploy --settings settings.xml
  - bash <(curl -s https://codecov.io/bash)