language: java
jdk:
  - oraclejdk8
sudo: false
install:
  - mvn clean install
  - mvn cobertura:cobertura
after_success:
  - mvn deploy --settings settings.xml
  - bash <(curl -s https://codecov.io/bash)